### ISSUE TITLE
Kurs kopieren

### ISSUE THREAD

**Issue by ruetscje** [schneisi/Dozentenverwaltung#10]
Beim kopieren von Kursen sollen auch ausgewählte Dozenten mit kopiert werden.
Achtung! Hier muss darauf geachtet werden, dass die auswahl der Radiobuttons nicht mit übernommen wird und somit der Status als grau angezeigt wird

**Comment by schneisi** [comment]
Müsste alles schon gehen. @ruetscje bei gelegenheit bitte mal testen.
Nur die Sache mit den Radio buttons ist noch gar nicht implementiert. Habe bei der Radio-Button-Issue Kommentar eingefügt, daher kann dieses Issue zu, oder?
