### ISSUE TITLE
Suche nach Kursen, Units, Dozenten, Modulen

### ISSUE THREAD

**Issue by ruetscje** [schneisi/Dozentenverwaltung#11]
Kurse, (Dozenten), Units und Module sollen selektiert werden können.
Am wichtigsten ist bei Units nach Quartalen

**Comment by schneisi** [comment]
@ruetscje was meinst du mit selektieren?

**Comment by ruetscje** [comment]
@schneisi das was Marco unbedingt wollte. Das er nach zb. Quartalen suchen kann bzw sortieren kann oder nach Kursen und dann alle Units oder Module für den Kurs angezeigt bekommt

**Comment by schneisi** [comment]
Nehme an Du meinst die Suche

**Comment by schneisi** [comment]
Pulle mal und schau ob alles drin ist so wie du es dir vorstellst
