### ISSUE TITLE
Bessere Multiselectbox

### ISSUE THREAD

**Issue by schneisi** [schneisi/Dozentenverwaltung#14]
Die aktuelle Multi select box ist nicht gut.
Schau mal ob du das eingebaut bekommst: https://www.codeseek.co/i_cant_rap/selectize-multiselect-with-bulma-qNdXyj

**Comment by ruetscje** [comment]
@schneisi habe den Select bei den Dozenten und der Unit geändert - falls es nicht passt kannst du das Issue wieder öffnen
