### ISSUE TITLE
Unit: Begin und Ende durch Jahr und Quartal ersetzen; Semester speichern

### ISSUE THREAD

**Issue by schneisi** [schneisi/Dozentenverwaltung#15]
1. Die Unit hat aktuell die Attribute BeginDate und EndDate. Das soll durch Jahr und Quartal ersetzt werden. Einfach beides als int speichern

2. Es gibt bereits das Attribut Semster, das wird aber noch nicht beschriben oder gelesen. Das sollte auch noch erledigt werden

**Comment by ruetscje** [comment]
Erledigt, ausserdem wurde die Suche noch angepasst damit auch nach Semester Jahr und Auartal gesucht werden kann (ob wir Semester drin lassen sollen können wir Marco ja noch fragen aber ich denke das ist ganz hilfreich wenn er zb alle erstsemester mit dem Titel BWL vergleichen will wegen dozenten
