### ISSUE TITLE
Prüfungsdetails in Unit eintragen

### ISSUE THREAD

**Issue by schneisi** [schneisi/Dozentenverwaltung#3]
In der Unit sollen auch Prüfungsdetails gespeichert werden. Dazu gehört unter anderem die Prüfungsart und die Prüfungsdauer. Model ist hierfür teilweise schon vorhanden. Hautaufgabe ist die GUI und die Builder zu modifizieren

**Comment by ruetscje** [comment]
Prüfungsart muss aus Drop Down Menü ausgewählt werden können
- Meiner Meinung nach erledigt oder @schneisi ?
