### ISSUE TITLE
Radiobox in Unit einfügen

### ISSUE THREAD

**Issue by ruetscje** [schneisi/Dozentenverwaltung#8]
Radiobox in die Unit einfügen:
gar kein Dozent eingertagen (rot) ist schon vorhanden
- nicht angefragt (grau)
- angrfragt (gelb)
-gesetzt (grün)

**Comment by schneisi** [comment]
Darauf achten dass damit beim Kopieren von Units richtig umgegangen wird

**Comment by ruetscje** [comment]
@schneisi darum wolltest du dich doch noch kümmern oder? ich setz das issue dann mal auf dich falls das falsch ist kannst du es mir ja wieder zuweisen
