### ISSUE TITLE
Dozentenauswahl in Unit

### ISSUE THREAD

**Issue by ruetscje** [schneisi/Dozentenverwaltung#9]
Es sollen über ein Drop Down Menü die Dozenten angezeigt werden, die dann als für die jeweilige Unit werden können.
Die Dozenten mit den nötigen Skills vollen hervorgehoben werden

**Comment by schneisi** [comment]
Dropdown gibt es schon, es wird aber noch nix hervorgehoben. Muss evtl auch anders gelöst werden

**Comment by schneisi** [comment]
@ruetscje pull mal und schau es dir an. Wenn nicht zufrieden mach die Issue wieder auf
